languageName: English
params:
  description: Why OpenMS? Mass Spectrometry. Visualizations. Open source.
  navbarlogo:
    image: openms-logo.png
    link: /
  hero:
    # Main hero title
    # title: OpenMS
    # Hero subtitle (optional)
    subtitle: The open-source framework for Mass Spectrometry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/install"
    # Hero image (from static/images/___)
    image: openms-logo.png
  pyopenms:
    title: Python Bindings
    subtitle: Python Folks 🐍 ! Get Started With pyOpenMS.
    buttontext: Get Started
    buttonlink: "/install/#pyopenms-installation"
    image: pyopenms.png

  keyfeatures:
    title: Features
    features:
    - title: Proteomics
      text: Almost 200 ready-made and customisable tools for analysing your proteomics data. Combined in flexible workflows they provide solutions to a broad range of problems arising in proteomics labs.
      img: /images/content_images/keyfeatures/proteomics.jpeg
      alttext: Lorem
      url: /keyfeatures/proteomics
    - title: Metabolomics
      text: OpenMS provides a wide range of customisable tools, specifically designed for all steps in the analysis of your targeted and untargeted metabolomics data.
      img: /images/content_images/keyfeatures/metabolomics.png
      url: /keyfeatures/metabolomics
    - title: Workflows
      text: Every tool that is developed within OpenMS is available on flexible, scalable and easy-to-use workflow engines (such as KNIME, Galaxy, and nextflow) facilitating reproducible science.
      img: /images/content_images/keyfeatures/workflows.png
      url: /keyfeatures/workflows
  # tabs:
  #   title: ECOSYSTEM
  section5: false


navbar:
  - title: Install
    url: /install
  - title: Documentation
    url: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html
  - title: Training
    url: /training
  - title: Community
    url: /community
  - title: About Us
    url: /about
  - title: Contribute
    url: /contribute
  - title: Use Cases
    url: /publications
    sublinks:
      - title: Applications
        url: /applications
      - title: Publications
        url: /publications
  - title: Help Request
    url: /help-request
    button: true
footer:
  title: OpenMS
  logo: 
  socialmediatitle: ""
  socialmedia:
  - link: https://github.com/OpenMS/OpenMS
    icon: github
  # - link: https://www.youtube.com/channel/
  #   icon: youtube
  - link: https://twitter.com/OpenMS_team
    icon: twitter
  quicklinks:
    column1:
      title: ""
      links:
        - text: Install
          link: /install
        - text: Documentation
          link: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/index.html
        - text: Citing OpenMS
          link: /citing-openms

    column2:
      links:
        - text: About us
          link: /about
        - text: Community
          link: /community
        - text: Contribute
          link: /contribute
        - text: Code of conduct
          link: /code-of-conduct
    column3:
      links:
        - text: Get help
          link: /gethelp
        - text: Terms of use
          link: /terms
        - text: Privacy
          link: /privacy
        - text: Press kit
          link: /press-kit

