languageName: English
params:
  description: Why OpenMS? Powerful n-dimensional arrays. Numerical computing tools. Interoperable. Performant. Open source.
  navbarlogo:
    image: logo.svg
    link: /
  hero:
    # Main hero title
    title: OpenMS
    # Hero subtitle (optional)
    subtitle: The fundamental package for scientific computing with Python
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/install"
    # Hero image (from static/images/___)
    image: logo.svg

  casestudies:
    title: CASE STUDIES
    features:
    - title: First Image of a Black Hole
      text: How OpenMS, together with libraries like SciPy and Matplotlib that depend on OpenMS, enabled the Event Horizon Telescope to produce the first ever image of a black hole
      img: /images/content_images/case_studies/blackhole.png
      alttext: First image of a black hole. It is an orange circle in a black background.
      url: /case-studies/blackhole-image
    - title: Detection of Gravitational Waves
      text: In 1916, Albert Einstein predicted gravitational waves; 100 years later their existence was confirmed by LIGO scientists using OpenMS.
      img: /images/content_images/case_studies/gravitional.png
      alttext: Two orbs orbiting each other. They are displacing gravity around them.
      url: /case-studies/gw-discov
    - title: Sports Analytics
      text: Cricket Analytics is changing the game by improving player and team performance through statistical modelling and predictive analytics. OpenMS enables many of these analyses.
      img: /images/content_images/case_studies/sports.jpg
      alttext: Cricket ball on green field.
      url: /case-studies/cricket-analytics
    - title: Pose Estimation using deep learning
      text: DeepLabCut uses OpenMS for accelerating scientific studies that involve observing animal behavior for better understanding of motor control, across species and timescales.
      img: /images/content_images/case_studies/deeplabcut.png
      alttext:  Cheetah pose analysis
      url: /case-studies/deeplabcut-dnn

  keyfeatures:
    features:
    - title: Proteomics
      text: Almost 200 ready-made and customisable tools for analysing your proteomics data. Combined in flexible workflows they provide solutions to a broad range of problems arising in proteomics labs.
    - title: Metabolomics
      text: OpenMS provides a wide range of customisable tools, specifically designed for all steps in the analysis of your targeted and untargeted metabolomics data.
    - title: Workflows
      text: Every tool that is developed within OpenMS is available on flexible, scalable and easy-to-use workflow engines (such as KNIME, Galaxy, and nextflow) facilitating reproducible science.
  tabs:
    title: ECOSYSTEM
  section5: false


navbar:
  - title: Install
    url: /install
  - title: Documentation
    url: https://OpenMS.org/doc/stable
  - title: Community
    url: /community
  - title: About Us
    url: /about
  - title: Contribute
    url: /contribute
  - title: Publications
    url: /publications
footer:
  logo: logo.svg
  socialmediatitle: ""
  socialmedia:
  - link: https://github.com/OpenMS/OpenMS
    icon: github
  - link: https://www.youtube.com/channel/UCguIL9NZ7ybWK5WQ53qbHng
    icon: youtube
  - link: https://twitter.com/OpenMS_team
    icon: twitter
  quicklinks:
    column1:
      title: ""
      links:
        - text: Install
          link: /install
        - text: Documentation
          link: https://OpenMS.org/doc/stable
        - text: Learn
          link: /learn
        - text: Citing OpenMS
          link: /citing-OpenMS
        - text: Roadmap
          link: https://OpenMS.org/neps/roadmap.html
    column2:
      links:
        - text: About us
          link: /about
        - text: Community
          link: /community
        - text: User surveys
          link: /user-surveys
        - text: Contribute
          link: /contribute
        - text: Code of conduct
          link: /code-of-conduct
    column3:
      links:
        - text: Get help
          link: /gethelp
        - text: Terms of use
          link: /terms
        - text: Privacy
          link: /privacy
        - text: Press kit
          link: /press-kit

